# Generated by Django 4.1.2 on 2022-10-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
